### ISSUE TITLE
plot principal components in descending order in scree plot

### ISSUE THREAD

**Issue by PaulEmily** [corybrunson/ordr#19]
Currently, when `ggplot()` is used to plot a scree plot for an augmented `prcomp()` object, the principal components are ordered alphabetically instead of in descending order.
```R
library(ordr)
pca <- augment(as_tbl_ord(prcomp(mtcars, center = TRUE, scale. = TRUE)))
pcacoord <- augmentation_coord(pca)
pcainertia <- recover_inertia(pca)
pcainertia <- data.frame(pcainertia = pcainertia)
pcacoord <- cbind(pcacoord, pcainertia)
ggplot(pcacoord, aes(x = .name, y = pcainertia/sum(pcainertia))) + geom_bar(stat = "identity") + scale_y_continuous(labels = scales::percent)
```
<img width="1440" alt="Screen Shot 2019-07-27 at 6 14 19 PM" src="https://user-images.githubusercontent.com/52010064/61999954-5d671680-b09a-11e9-9ecd-cc8a2b212e79.png">

**Comment by corybrunson** [comment]
Thanks for raising this issue! I can reproduce the behavior, and i'm working on a fix.

**Comment by corybrunson** [comment]
Note about the fix: `augmentation_coord()` now stores the coordinate names as a factor variable. `fortify()` calls this function when `.matrix = "coordinates"`, and `ggplot()` calls `fortify()` in turn. While the fix wouldn't be appropriate for `augmentation_u()` and `augmentation_v()`, it's very appropriate here because most matrix factorizations used in practice are hierarchical, in that each coordinate is the most "important" except for the previous ones.
